name: Docker build & push to GHCR

on:
  workflow_dispatch:            # manual runs allowed
  push:
    branches: [master]          # after merge to master
  pull_request:                 # PRs = build-only

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug refs
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR (only on master)
        if: ${{ github.ref_name == 'master' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (PR) or Build+Push (master)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          # ✅ pushes for: push to master AND manual runs targeting master
          push: ${{ github.ref_name == 'master' }}
          tags: |
            ghcr.io/irctrakz/wgserver:latest
            ghcr.io/irctrakz/wgserver:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
